name: Merge

on:
  push:
    branches:
      - master

jobs:
  flatpak:
    name: "Flatpak"
    runs-on: ubuntu-latest
    container:
      image: ghcr.io/flathub-infra/flatpak-github-actions:gnome-48
      options: --privileged
    steps:
      - uses: actions/checkout@v4
      - uses: flatpak/flatpak-github-actions/flatpak-builder@v6
        with:
          bundle: planify.Devel.flatpak
          manifest-path: build-aux/io.github.alainm23.planify.Devel.json
          cache-key: flatpak-builder-${{ github.sha }}

  gettext_template:
    runs-on: ubuntu-latest

    steps:
      - name: Clone repository
        uses: actions/checkout@v4
        with:
          token: ${{ secrets.GIT_USER_TOKEN }}

      - name: Update Translation Files
        uses: elementary/actions/gettext-template@main
        env:
          GIT_USER_TOKEN: ${{ secrets.GIT_USER_TOKEN }}
          GIT_USER_NAME: "elementaryBot"
          GIT_USER_EMAIL: "builds@elementary.io"
