---
name: Merge

on:
  push:
    branches:
      - master

name: CI
jobs:
  flatpak:
    name: "Flatpak"
    runs-on: ubuntu-latest
    container:
      image: ghcr.io/flathub-infra/flatpak-github-actions:gnome-48
      options: --privileged
    steps:
      - uses: actions/checkout@v4
      - uses: flatpak/flatpak-github-actions/flatpak-builder@v6
        with:
          bundle: planify.Devel.flatpak
          manifest-path: build-aux/io.github.alainm23.planify.Devel.json
          cache-key: flatpak-builder-${{ github.sha }}
    gettext:
      name: Gettext
      runs-on: ubuntu-latest
      container:
        image: ghcr.io/flathub-infra/flatpak-github-actions:gnome-47
        options: --privileged

      steps:
        - name: Install git, python3-git and jq
          run: |
            apt-get update
            apt-get install git jq python3-git -y

        - name: Clone repository
          uses: actions/checkout@v4
          with:
            token: ${{ secrets.GIT_USER_TOKEN }}

        - name: Install Rust SDK extension
          run: |
            flatpak remote-add --if-not-exists flathub https://flathub.org/repo/flathub.flatpakrepo
            flatpak install -y org.freedesktop.Sdk.Extension.rust-stable//23.08

        - name: Configure Git
          run: |
            git config --global --add safe.directory "$GITHUB_WORKSPACE"
        - name: Update Translation Files
          uses: elementary/actions/gettext-flatpak@main
          with:
            manifest-path: "io.github.alainm23.planify.json"
          env:
            GIT_USER_NAME: "elementaryBot"
            GIT_USER_EMAIL: "builds@elementary.io"
